# cluster_config.yml - cluster configuration
__default__:
  account: sansam-lab
  partition: serial
  time: "08:00:00"
  cpus-per-task: 2
  mem: "16G"
  output: logs/slurm-%x.%A.%a.log
  error: logs/slurm-%x.%A.%a.err

fastqc_raw:
  time: "00:30:00"
  cpus-per-task: 1
  mem: "4G"

multiqc_raw:
  time: "00:15:00"
  cpus-per-task: 1
  mem: "2G"

trim_adapters:
  time: "01:00:00"
  cpus-per-task: 2
  mem: "8G"

align_hisat2:
  time: "04:00:00"
  cpus-per-task: 8
  mem: "32G"
