## samples file
samples_csv: "config/samples.csv"

# ==============================================================================
# ADAPTER FILE (Cutadapt)
# ==============================================================================
TruSeq3_Adapters: "/resources/truseq_universal_adapters.fa"

# ==============================================================================
# HISAT2 GENOME
# ==============================================================================
# Primary genome = GRCz11
Hisat2_Index: "/hpc-prj/cobre-dev-bio/boydk/reference_info/hisat2_index/GRCz11"


# ==============================================================================
# SOFTWARE MODULE VERSIONS
# ==============================================================================
fastqc: "fastqc/0.12.1"
multiqc: "multiqc/1.21"
cutadapt: "cutadapt/5.0"
hisat2: "hisat2/2.2.1"
samtools: "samtools/1.18"
