## samples file
samples_csv: "config/samples.csv"

# ==============================================================================
# ADAPTER FILE (Cutadapt)
# ==============================================================================
TruSeq3_Adapters: "/resources/truseq_universal_adapters.fa"

# ==============================================================================
# HISAT2 ALIGNMENT
# ==============================================================================
# Primary genome = GRCz11
Hisat2_Index: "/hpc-prj/cobre-dev-bio/boydk/reference_info/hisat2_index/GRCz11"

# ==============================================================================
# HISAT2 GENOME
# ==============================================================================
Annotation_GTF: "/s/cobre-dev-bio/boydk/Varshney_Lab/genomic_resources/ncbi_dataset/data/GCF_000002035.6/genomic.gtf"

# ==============================================================================
# SOFTWARE MODULE VERSIONS
# ==============================================================================
fastqc: "fastqc/0.12.1"
multiqc: "multiqc/1.21"
fastp: "fastp/0.23.4"
hisat2: "hisat2/2.2.1"
samtools: "samtools/1.18"
subread: "subread/1.6.3"
